package hbi.core.om.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import java.util.Date;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "hap_inv_inventory_items")
public class InvInventoryItems extends BaseDTO {
    @Id
    @GeneratedValue
    private Long inventoryItemId;

    @Column
    @NotEmpty
    private String itemCode;

    @Column
    @NotEmpty
    private String itemUom;

    @Column
    @NotEmpty
    @Condition(operator = "LIKE")
    private String itemDescription;

    @Column
    @NotEmpty
    private String orderFlag;

    @Column
    private Date startActiveDate;

    @Column
    private Date endActiveDate;

    @Column
    @NotEmpty
    private String enabledFlag;


    public void setInventoryItemId(Long inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    public Long getInventoryItemId() {
        return inventoryItemId;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemCode() {
        return itemCode;
    }

    public void setItemUom(String itemUom) {
        this.itemUom = itemUom;
    }

    public String getItemUom() {
        return itemUom;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public String getItemDescription() {
        return itemDescription;
    }

    public void setOrderFlag(String orderFlag) {
        this.orderFlag = orderFlag;
    }

    public String getOrderFlag() {
        return orderFlag;
    }

    public void setStartActiveDate(Date startActiveDate) {
        this.startActiveDate = startActiveDate;
    }

    public Date getStartActiveDate() {
        return startActiveDate;
    }

    public void setEndActiveDate(Date endActiveDate) {
        this.endActiveDate = endActiveDate;
    }

    public Date getEndActiveDate() {
        return endActiveDate;
    }

    public void setEnabledFlag(String enabledFlag) {
        this.enabledFlag = enabledFlag;
    }

    public String getEnabledFlag() {
        return enabledFlag;
    }


}
