package hbi.core.om.dto;

/**
 * Auto Generated By Hap Code Generator
 **/

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.mybatis.annotation.ExtensionAttribute;

import javax.persistence.Table;

import com.hand.hap.system.dto.BaseDTO;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;

@ExtensionAttribute(disable = true)
@Table(name = "hap_om_order_lines")
public class OmOrderLines extends BaseDTO {
    @Id
    @GeneratedValue
    private Long lineId;

    @Column
    @NotNull
    private Long headerId;

    @Column
    @NotNull
    private Long lineNumber;

    @Column
    @NotNull
    private Long inventoryItemId;
    @Column
    @NotNull
    private Long orderdQuantity;
    @Column
    @NotEmpty
    private String orderQuantityUom;
    @Column
    @NotNull
    private Long unitSellingPrice;
    @Column
    @NotEmpty
    private String description;
    @Column
    @NotNull
    private Long companyId;
    @Column
    private String addition1;
    @Column
    private String addition2;
    @Column
    private String addition3;
    @Column
    private String addition4;
    @Column
    private String addition5;


    public void setLineId(Long lineId) {
        this.lineId = lineId;
    }

    public Long getLineId() {
        return lineId;
    }

    public void setHeaderId(Long headerId) {
        this.headerId = headerId;
    }

    public Long getHeaderId() {
        return headerId;
    }

    public void setLineNumber(Long lineNumber) {
        this.lineNumber = lineNumber;
    }

    public Long getLineNumber() {
        return lineNumber;
    }

    public void setInventoryItemId(Long inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    public Long getInventoryItemId() {
        return inventoryItemId;
    }

    public void setOrderdQuantity(Long orderdQuantity) {
        this.orderdQuantity = orderdQuantity;
    }

    public Long getOrderdQuantity() {
        return orderdQuantity;
    }

    public void setOrderQuantityUom(String orderQuantityUom) {
        this.orderQuantityUom = orderQuantityUom;
    }

    public String getOrderQuantityUom() {
        return orderQuantityUom;
    }

    public void setUnitSellingPrice(Long unitSellingPrice) {
        this.unitSellingPrice = unitSellingPrice;
    }

    public Long getUnitSellingPrice() {
        return unitSellingPrice;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    public Long getCompanyId() {
        return companyId;
    }

    public void setAddition1(String addition1) {
        this.addition1 = addition1;
    }

    public String getAddition1() {
        return addition1;
    }

    public void setAddition2(String addition2) {
        this.addition2 = addition2;
    }

    public String getAddition2() {
        return addition2;
    }

    public void setAddition3(String addition3) {
        this.addition3 = addition3;
    }

    public String getAddition3() {
        return addition3;
    }

    public void setAddition4(String addition4) {
        this.addition4 = addition4;
    }

    public String getAddition4() {
        return addition4;
    }

    public void setAddition5(String addition5) {
        this.addition5 = addition5;
    }

    public String getAddition5() {
        return addition5;
    }

}
